from __future__ import annotations

from .schemas import (
    UniversalConfig,
    UniversalConfig as ScraperConfig,  # Backward compatibility alias
    UniversalRequest,
    UniversalResult,
    SiteProfile,
    DeepSiteProfile,
    FallbackContext,
    GenerationStrategy,
    GeneratedScript,
    ValidationResult,
    GenerationMetadata,
    CachedScript,
    CacheEntry,
    FailureClassification,
    EngineAttempt,
    EngineMetrics,
    OrchestratorPoolConfig,
    HealthCheckResult,
    EngineType,
    OutputFormat,
    StateBackend,
    ExecutionMode,
    ProfileDepth,
    ValidationMode,
    AntiBotLevel,
    ProxyType,
    BrowserType,
    LogLevel,
    TaskPriority,
    QueueConfig,
    WorkerConfig,
    CheckpointConfig,
)

from .loader import (
    ConfigLoader,
    load_config,
    load_config_from_file,
    merge_configs,
    get_default_config,
    get_low_memory_config,
    validate_config,
    create_argument_parser,
)

__all__ = [
    "UniversalConfig",
    "ScraperConfig",  # Backward compatibility
    "UniversalRequest",
    "UniversalResult",
    "SiteProfile",
    "DeepSiteProfile",
    "FallbackContext",
    "GenerationStrategy",
    "GeneratedScript",
    "ValidationResult",
    "GenerationMetadata",
    "CachedScript",
    "CacheEntry",
    "FailureClassification",
    "EngineAttempt",
    "EngineMetrics",
    "OrchestratorPoolConfig",
    "HealthCheckResult",
    "EngineType",
    "OutputFormat",
    "StateBackend",
    "ExecutionMode",
    "ProfileDepth",
    "ValidationMode",
    "AntiBotLevel",
    "ProxyType",
    "BrowserType",
    "LogLevel",
    "TaskPriority",
    "QueueConfig",
    "WorkerConfig",
    "CheckpointConfig",
    "ConfigLoader",
    "load_config",
    "load_config_from_file",
    "merge_configs",
    "get_default_config",
    "get_low_memory_config",
    "validate_config",
    "create_argument_parser",
]